### ISSUE TITLE
Question about accession2taxid

### ISSUE THREAD

**Issue by foreignsand** [sanger-tol/ascc#66]
The yaml file fed to ascc needs to contain the path to accession2taxid and there are [many different accession2taxid options](https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/) listed at NCBI. Which one(s) should be used for running the ascc pipeline?

Cheers

**Comment by eeaunin** [comment]
Hello. I'm happy to see that someone on GitHub is trying to run ASCC. There is a description of how to install the databases for ASCC here: [https://github.com/sanger-tol/ascc/blob/ea10_documentation_edits2/docs/databases.md](https://github.com/sanger-tol/ascc/blob/ea10_documentation_edits2/docs/databases.md). This includes the list of accession2taxid files that need to be downloaded. 
The https://github.com/sanger-tol/ascc/tree/ea10_documentation_edits2 branch has also more documentation files than the dev branch.
To test if you can get the pipeline to run without crashes you may want to try running it with tiny test files first, as described in [https://github.com/sanger-tol/ascc/tree/ea10_documentation_edits2](https://github.com/sanger-tol/ascc/tree/ea10_documentation_edits2).
If you run into more problems, let us know. An older version of ASCC that is not public is used routinely in the Sanger Institute's Tree of Life for contamination checks. The new version of ASCC that is at here at https://github.com/sanger-tol/ascc is still a bit rough but we're working on fixing any issues that crop up with it

**Comment by foreignsand** [comment]
fantastic! thank you so much for the prompt and thorough reply! i learned about the ascc pipeline while attending the physalia genome curation course taught by michael and camilla. it was fantastic and made me realize how much more i need to learn. 

thanks again! i'm sure i'll be back with more questions as i get this running on my university's hpc cluster.
