### ISSUE TITLE
Layer 2 - Kmer Counting + dim reduction

### ISSUE THREAD

**Issue by DLBPointon** [sanger-tol/ascc#7]
Implement Eerik's version and 
A future task will be implementing a version using FastK, then compare.

**Comment by weaglesBio** [comment]
https://github.com/sanger-tol/cobiontcheck/blob/develop/ascc_get_kmer_counts.py
https://github.com/sanger-tol/cobiontcheck/blob/develop/ascc_dim_reduction.py

**Comment by DLBPointon** [comment]
KMER may need to split out so that there is an instance per machine learning method.
